name: Deploy feature branches to nonproduction bucket

on:
  push:
    branches:
      - feature*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: configure aws cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secret.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secret.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: build site
        run: |
          npm ci
          npm run build
      - name: deploy site to bucket
        run: aws s3 cp public s3://${ secrets.AWS_S3_NONPROD }}/ --recursive --acl public-read